app:
  secrets:
    use-aws: true
aws:
  secrets:
     names: application_math_assistant
server:
  forward-headers-strategy: framework

# Comma-separated AWS secret names to load (do NOT store secrets here)
# aws.secrets.names: my/secret/name,other/secret
