spring.application.name=MathExpAssistant
spring.security.oauth2.client.registration.google.client-id=725763403103-75t30b4pa7j4a7n615qf82pahvkanm83.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
